services:
  my-jekyll-container:
    build: .
    restart: always
    tty: true
    volumes:
      - ./app:/app
      - ./conf:/etc/nginx/conf.d # For nginx setting
    ports:
      - "4000:4000"
networks:
  my-jekyll-network:
    driver: bridge