services:
  jekyll:
    image: jekyll-site:latest
    build:
      context: .
    restart: always
    container_name: mschultheiss83githubio
    volumes:
      - .:/usr/src/app
      - ./_site:/usr/src/app/_site
    ports:
      - "4000:4000"
    command: bundle exec jekyll serve --host 0.0.0.0 --watch